### ISSUE TITLE
Upload pictures from app to site

### ISSUE THREAD

**Issue by iDolmatov** [stalkerg/anime-pictures-app#14]
Maybe?

**Comment by stalkerg** [comment]
Upload pictures from app?

**Comment by iDolmatov** [comment]
From android device to site

**Comment by iDolmatov** [comment]
Не все пользуются компьютером для выхода в интернет, может кто и захочет загрузить картинку. Хотя, в основном удобно это делать только с большим экраном на планшете

**Comment by stalkerg** [comment]
I have one problem only: form for put tags.

**Comment by iDolmatov** [comment]
Увы, насколько API позволяет делать подсказки (как при наборе текста с некоторым клавиатурами) не знаю. Так-же если делать запрос к сайты это может сказаться на трафике, а постоянная синхронизация файла тегов ещё и на хранимом объёме тегов в файле с производительностью. В принципе, я уточнял лишь такую возможность, ведь если и возможно, то нужно качественно проработать механизм и сразу определить будет ли такой вариант загрузки популярен (ведь место не так много на телефонах\планшетах)

**Comment by stalkerg** [comment]
Никаких проблем с API нету и трафика это много не жрёт (всё работает как тонкий клиент). Но всё же это очень странно грузить картинку с телефона т.к. как то её туда ещё надо загрузить, а это уже не всегда тривиально.

**Comment by iDolmatov** [comment]
Так да, идея сомнительная. Поэтому в форме вопроса топик.
Topic closed.
