### ISSUE TITLE
update checker

### ISSUE THREAD

**Issue by ahjolinna** [stalkerg/anime-pictures-app#16]
if this app won't be available on play store on somewhere else (like amazon), you should add update checker and download/installer, like firefox aurora version has or the Manga Rock (definitive version) app that also got removed from play store (sigh)

**Comment by stalkerg** [comment]
Thanks for this issue but I have already done it for 1.12.0 version. :)

**Comment by ahjolinna** [comment]
oh I didnt notice that, maybe u could add a about page or something where the version number is and have an option for checking the updates manually
