### ISSUE TITLE
Downloading images issue

### ISSUE THREAD

**Issue by Pegasrider** [stalkerg/anime-pictures-app#17]
Hello. New phone Xiaomi MiMax, android 6.0.1. MUI 8 6.9.1 beta. Language Russian. When pressed "Download" button some message pop:
Включите Документы в настройках >Установленные приложения
Same message when trying to set a flag "use default folder".

The only way to save image - tap on picture, "Move to..." and to select a folder to save. How can I use a more... simple way to download images?

**Comment by stalkerg** [comment]
It is bug in MIUI. You can turn on this app:
https://www.youtube.com/watch?v=Ik2DJ6-kf3I 

PS I have Xiaomi Redme Note 3 Pro

**Comment by stalkerg** [comment]
Has it helped you?

**Comment by Pegasrider** [comment]
Yes, that helped, thank you very much!
