### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ChekaLI** [stalkerg/anime-pictures-app#22]
В общем суть такая, при переходе на тэг (azur lane) а точнее на картинку ( https://anime-pictures.net/pictures/view_post/539794?lang=ru ) только из приложения, случается баг, при котором не отображается кнопка добавить в избранное (после этой картинки на всех последующих) и производится как я понимаю полный выброс с аккаунта до следующего релога приложения и повторной авторизации в нём. При новых последующих переходах к той картинке повторяется аналогичное явление(проверил несколько раз), при том на самой картинке есть счётчик звёзд в вэб-версии он работает а в приложении пишет 0.
upd: Ссылка на картинку не верная, в приложении высвечивается 2 версия этой картинки с ню содержанием, на саму картинку осуществить переход даже в вэб-версии нет возможности, просиходит переход на изображение что выше указано в скобках.

**Comment by stalkerg** [comment]
Спасибо за найденный баг!
Мы поправили картинку, проверьте пожалуйста. 
Кроме того не могли бы вы сказать версию приложения?

**Comment by ChekaLI** [comment]
ой и правда про версию забыл написать, 1.12.3
Проверил, теперь всё стабильно работает.

**Comment by ChekaLI** [comment]
В общем и целом, в данный момент в приложении "любое" изображение( проверил первую десятку) выкидывает с аккаунта, то есть аналогично с той же проблемой что была ранее мной указана, но с большим покрытием по картинкам. Приложение последнее с сайта, для большей уверенности - 1) для начала стёр кэш в приложении и сбросил все данные (результат: баг присутствует); 2) Переустановил приложение с сайта (проблема осталась);

**Comment by stalkerg** [comment]
Подтверждаю, выявилось у многих.

**Comment by stalkerg** [comment]
Нашёл и исправил ошибку. В ближайшие дни будет обновление.

**Comment by stalkerg** [comment]
Проверьте в новой версии.

**Comment by ChekaLI** [comment]
С новой версией полёт нормальный.
