### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by ghost** [stalkerg/anime-pictures-app#23]
I log in with Google account with all my things on. If I view any picture it will stop me from accessing my favourite folders and if I click to "star" a photo it will send me back to the login screen.

 Also on login it says "this application is authorized, start authentication server"

**Comment by ghost** [comment]
Also if I try to login on web page it sends me to a blank page saying "Not Have Token"

**Comment by stalkerg** [comment]
What version of application do you use?

**Comment by Holzy32** [comment]
I'm using version Last version: 1.12.3 and I'm having the same issue

**Comment by stalkerg** [comment]
Thanks for your issue I can reproduce. Same as #22 .
I will fix it ASAP.

**Comment by stalkerg** [comment]
I find and fix a problem. I think I will make a new version in next 2 days.

**Comment by bibuborg** [comment]
Getting same issue

**Comment by stalkerg** [comment]
Please, try a new version.

**Comment by Holzy32** [comment]
Did you update the link? I download it from the site but it keeps installing the older version

**Comment by stalkerg** [comment]
I just copy another file... sorry, now should be fine.

**Comment by stalkerg** [comment]
@Holzy32 can you try again?

**Comment by ghost** [comment]
Thank you @stalkerg
Issue resolved.

**Comment by Holzy32** [comment]
Got it thanks
