### ISSUE TITLE
Favorites not working

### ISSUE THREAD

**Issue by MiTereKun** [stalkerg/anime-pictures-app#25]
после обновления на 1.12.4, без каких-либо признаков, меню _избрать_ стало неработоспособным. В нём по прежнему есть список моих папок, при выборе папки - так же автоматически ставится звезда на картинку и пишется "добавить в избранные **В Папка п..**", но, если зайти на картинку снова - в этом меню отображается первоначальная надпись  "добавить в избранные **Не в избра..**", и, соответственно картинка не избирается вовсе, но звезда ставиться. Благодаря этому сейчас быстро нашёл те картинки. Ещё раз спасибо за сортировку в звёздах по времени "звездания".
Удаление кеша и переустановка приложения не помогли.

**Comment by stalkerg** [comment]
Подверждаю. Поправлю. Похоже  не работает именно добавление в избранное.

**Comment by stalkerg** [comment]
пофиксил.
