### ISSUE TITLE
Can't open images

### ISSUE THREAD

**Issue by gamer2key** [stalkerg/anime-pictures-app#26]
I can't open images from the notification when I save them in memory. Ah, is it possible to see the images which you left a star from the application? it would be super convenient!
I have a p10 with the latest version of the app and android.

**Comment by stalkerg** [comment]
Please check new version.

**Comment by stalkerg** [comment]
> Ah, is it possible to see the images which you left a star from the application? it would be super convenient!

I think I can add this filter.

**Comment by gamer2key** [comment]
New version opens the gallery perfectly! :) yes, it would be great to have that filter!
