### ISSUE TITLE
Pictures do no show up

### ISSUE THREAD

**Issue by Catronimes** [stalkerg/anime-pictures-app#30]
In the latest version 1.12.8 i cant see any of the pictures in the app, no previews, no picture after clicking on it. I have android version 4.4.2 and a samsung honor.
I really love this app and their pictures, but if i cant use the app any more its like the end of the world. And i cant even downgrade to previous version.
Please fix this problem as fast as possible.
Best regards
Cat

**Comment by stalkerg** [comment]
Hello! Thanks for the issue.
Looks like it's tied with https://github.com/square/okhttp/issues/4053

**Comment by stalkerg** [comment]
Do you have color squares and pages?

**Comment by stalkerg** [comment]
@Catronimes please, check new version.

**Comment by Catronimes** [comment]
Wow, this was really fast, its working perfect now. Thank you very much :)
"Do you have color squares and pages?" Yes i had them

 
--




 
--
