### ISSUE TITLE
No tips for tags/Нет подсказок для тегов

### ISSUE THREAD

**Issue by Rikutoku** [stalkerg/anime-pictures-app#33]
Раньше появлялись подсказки на русском или аноглийском когда пишешь часть тега в поиске, месяца два-три назат пропали.
Пробовал два устройства:
Nokia 6 (2017) Android 9.0.0,
Pantech Sky Vega Android 4.4.2 / 5.0.1 / 7.0.1 (разные прошивки были)

Previously, prompts appeared in Russian or English when you write part of a tag in a search, two or three months have disappeared.
I tried two devices:
Nokia 6 (2017) Android 9.0.0,
Pantech Sky Vega Android 4.4.2 / 5.0.1 / 7.0.1 (there were different firmware)

![S90809-230556](https://user-images.githubusercontent.com/53950638/62799492-5d373400-bafa-11e9-8826-414b789bf63f.jpg)

**Comment by stalkerg** [comment]
Спасибо! Скоро поправлю.

**Comment by stalkerg** [comment]
Поправил, проверяйте.

**Comment by Rikutoku** [comment]
Все работает, спасибо.
